[project]
name = "viet-ocr-lite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "protonx>=0.1.8",
    "pydantic-settings>=2.13.1",
    "pypdf>=6.7.3",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
]
